platform :ios, '9.0'

target 'URBNSwiftyConvenience_Example' do
  pod 'URBNSwiftyConvenience', :path => '../'
end

target 'URBNSwiftyConvenience_Tests' do
  pod 'URBNSwiftyConvenience', :path => '../'
end
