platform :ios, '10.0'

use_frameworks!

target 'URBNSwiftyConvenience_Example' do
  pod 'URBNSwiftyConvenience', :path => '../'

  target 'URBNSwiftyConvenience_Tests' do
    inherit! :search_paths


  end
end
