# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: objective-c
xcode_project: Example/URBNSwiftyConvenience.xcworkspace
xcode_sdk: iphonesimulator12.0
xcode_scheme: URBNSwiftyConvenience-Example
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
# cache: cocoapods
podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
# script:
# - set -o pipefail && xcodebuild test -workspace Example/URBNSwiftyConvenience.xcworkspace -scheme URBNSwiftyConvenience-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint
